# Generated by Django 5.0.8 on 2024-09-12 17:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("openapp", "0002_alter_chatgptbot_options_chatgptbot_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatgptbot",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Messages History",
                "verbose_name_plural": "Messages History",
            },
        ),
    ]
